name: transipy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        python-version: 3.9
        auto-update-conda: true

    - name: Set Conda solver to classic and disable plugins
      run: |
        conda config --set solver classic
        CONDA_NO_PLUGINS=true conda env update --file environment.yml --name base

    - name: Install additional pip dependencies
      run: |
        source activate base
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source activate base
        pytest
